### ISSUE TITLE
Profile UI

### ISSUE THREAD

**Issue by mariawaseem** [Konica-l/CSE110-Project#33]
@mariawaseem @MichelleW1234 Develop UI for profile, make consistent with other pages

**Comment by MichelleW1234** [comment]
Finished user's schedule mockup (commit https://github.com/Konica-l/CSE110-Project/commit/ac5edbc2e9ce930e75c85ae37d3de711279b227f)

**Comment by MichelleW1234** [comment]
Finished user's schedule mockup (commit https://github.com/Konica-l/CSE110-Project/commit/ac5edbc2e9ce930e75c85ae37d3de711279b227f)
